  GNU nano 6.2                                      docker-compose.production.yml
version: '3.3'
volumes:
  postgres_data:
  static_value:
  media_value:

services:
  frontend:
    image: foxa26/frontend_foodgram
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_value:/app/result_build/
    depends_on: backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - frontend
    env_file:
      - .env

  backend:
    image: foxa26/foodgram_backend
    restart: always
    volumes:
      - static_value:/backend_static
      - media_value:/backend_media
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: foxa26/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - static_value:/backend_static
      - media_value:/backend_media
    depends_on:
      - backend
