version: '3.3'
volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
      image: postgres:13
      volumes:
        - /var/lib/postgresql/data/
      depends_on:
        - frontend
      env_file:
        - ./.env

  backend:
    image: foxa26/foodgram_backend
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: foxa26/frontend_foodgram
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: foxa26/foodgram_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - backend

