version: '3.3'
volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
      image: postgres:13
      volumes:
        - /var/lib/postgresql/data/
      depends_on:
        - frontend
      env_file:
        - .env

  backend:
    image: foxa26/foodgram_backend
    restart: always
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: foxa26/foodgram_frontend
    volumes:
      - static:/frontend_static

  nginx:
    image: foxa26/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - backend

