version: '3.3'
volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
      image: postgres:13
      volumes:
        - /var/lib/postgresql/data/
      depends_on:
        - frontend
      env_file:
        - .env

  backend:
    image: foxa26/foodgram_backend
    restart: always
    volumes:
      - static_value:/backend_static
      - media_value:/backend_media
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: foxa26/frontend_foodgram
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_value:/frontend_static

  nginx:
    image: foxa26/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - static_value:/backend_static
      - media_value:/backend_media
    depends_on:
      - backend
